[project]
name = "Winnie"
description = "RDI PSF subtraction and forward modeling for high-contrast imaging data"
authors = [{ name = "Kellen Lawson", email = "kellenlawson@gmail.com" },]
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Topic :: Scientific/Engineering :: Astronomy",
    "Programming Language :: Python",
    "Intended Audience :: Science/Research",
    ]
dependencies = [
    "astropy",
    "joblib",
    "jwst",
    "lmfit",
    "matplotlib",
    "numpy",
    "photutils",
    "pyklip",
    "scipy",
    "scikit-learn",
    "spaceKLIP",
    "tqdm",
    "vip_hci", 
    "stpsf",
    "webbpsf_ext",
    ]


[project.optional-dependencies]
tutorials = ["synphot",]
gpu = ["cupy",]   


[project.urls]
github_project = "https://github.com/kdlawson/Winnie"


[build-system]
requires = [
    "setuptools >= 61.2",
    "setuptools_scm[toml]>=3.4.3",
    "wheel",
    ]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "winnie/_version.py"


[tool.setuptools.package-data]
winnie = ["resources/*"]